# Generated by Django 3.2.4 on 2021-06-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
            ],
        ),
    ]
